services:
  - name: gofish-app
    type: web
    env: node

    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build

    startCommand: node backend/index.js

    staticPublishPath: frontend/dist

    plan: free
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      # Uncomment and add your OpenWeather key if needed:
      # - key: OPENWEATHER_API_KEY
      #   value: your-api-key-here